version: 1.0.0.{build}
image:
  - Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
skip_branch_with_pr: true
configuration: Release
before_build:
  - cmd: dotnet restore
build:
  verbosity: minimal
  parallel: true
artifacts:
  - path: '**\*.nupkg'
nuget:
  disable_publish_on_pr: true
#deploy:
#  provider: NuGet
#  api_key:
#    secure: <Your secret>
